[patch.crates-io]
frame-benchmarking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
frame-benchmarking-cli = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
frame-executive = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
frame-support = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
frame-system = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
frame-system-benchmarking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
frame-system-rpc-runtime-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-balances = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-democracy = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-election-provider-multi-phase = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-grandpa = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-identity = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-randomness-collective-flip = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-scheduler = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-sudo = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-timestamp = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-tips = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-transaction-payment-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-transaction-payment-rpc-runtime-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-basic-authorship = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-chain-spec = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-cli = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-client-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-client-db = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-consensus = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-consensus-epochs = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-executor = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-finality-grandpa = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-informant = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-keystore = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-network = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-offchain = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-rpc-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-service = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-telemetry = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-transaction-pool = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-application-crypto = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-arithmetic = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-block-builder = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-blockchain = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-consensus = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-core = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-externalities = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-finality-grandpa = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-inherents = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-io = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-offchain = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-runtime = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-runtime-interface = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-session = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-staking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-state-machine = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-std = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-storage = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-timestamp = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-tracing = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-transaction-pool = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-trie = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-version = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-npos-elections = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
substrate-frame-rpc-system = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}

pallet-transaction-payment = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}

#staking
pallet-authority-discovery = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-authorship = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-babe = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-collective = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-elections-phragmen = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-im-online = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-offences = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-session = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-staking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-staking-reward-curve = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-treasury = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
pallet-utility = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-authority-discovery = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.5'}
sc-consensus-babe = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-consensus-babe-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sc-consensus-slots = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.5'}
sc-consensus-uncles = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.5'}
sp-authority-discovery = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-consensus-babe = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5'}
sp-keystore = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.5'}
sp-authorship = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.5'}

# ORML dependencies
orml-currencies = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ded28318c23e2d263beeb1235f040f51826fe11e'}
orml-tokens = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ded28318c23e2d263beeb1235f040f51826fe11e'}
orml-traits = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ded28318c23e2d263beeb1235f040f51826fe11e'}
orml-utilities = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ded28318c23e2d263beeb1235f040f51826fe11e'}

[profile.release]
panic = 'unwind'

[workspace]
members = [
  # 'pallets/proposal', Update this
  'node',
  'pallets/asset-registry',
  'pallets/exchange',
  'pallets/transaction-multi-payment',
  'pallets/genesis-history',
  'pallets/xyk',
  'pallets/price-fetch',
  'primitives',
  'runtime',
  'utils/build-script-utils'
]
